import type { Metadata } from "next";
import "./globals.css";
import RouteGuard from "./RouteGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <RouteGuard>
          {children}
        </RouteGuard>
      </body>
    </html>
  );
}
