import type { Metadata } from "next";
import "./globals.css";
import RouteGuard from "./RouteGuard";
import { Shell } from "../components/Shell";

export const metadata: Metadata = {
  title: "PaxFide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body>
        <RouteGuard>
          <Shell>
            {children}
          </Shell>
        </RouteGuard>
      </body>
    </html>
  );
}
